// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Giy771lEl3oe_U_kIk40wQ3TNR3AR8s',
    appId: '1:1095663954442:web:6c5b0d8e5551083dff4df3',
    messagingSenderId: '1095663954442',
    projectId: 'smart-traffic-light-03',
    authDomain: 'smart-traffic-light-03.firebaseapp.com',
    databaseURL: 'https://smart-traffic-light-03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-light-03.firebasestorage.app',
    measurementId: 'G-PZ6XR62D82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW-ePShshPrRmWG2iCXtTtSQDu8y4QyPg',
    appId: '1:1095663954442:android:00fd4a673627b962ff4df3',
    messagingSenderId: '1095663954442',
    projectId: 'smart-traffic-light-03',
    databaseURL: 'https://smart-traffic-light-03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-light-03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIYTVzlwE587Yi1JT6lqqkfTpgvwtu0G8',
    appId: '1:1095663954442:ios:95177e3aa00914b3ff4df3',
    messagingSenderId: '1095663954442',
    projectId: 'smart-traffic-light-03',
    databaseURL: 'https://smart-traffic-light-03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-light-03.firebasestorage.app',
    iosBundleId: 'com.example.traffic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIYTVzlwE587Yi1JT6lqqkfTpgvwtu0G8',
    appId: '1:1095663954442:ios:95177e3aa00914b3ff4df3',
    messagingSenderId: '1095663954442',
    projectId: 'smart-traffic-light-03',
    databaseURL: 'https://smart-traffic-light-03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-light-03.firebasestorage.app',
    iosBundleId: 'com.example.traffic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Giy771lEl3oe_U_kIk40wQ3TNR3AR8s',
    appId: '1:1095663954442:web:adcff0a5f624de41ff4df3',
    messagingSenderId: '1095663954442',
    projectId: 'smart-traffic-light-03',
    authDomain: 'smart-traffic-light-03.firebaseapp.com',
    databaseURL: 'https://smart-traffic-light-03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-traffic-light-03.firebasestorage.app',
    measurementId: 'G-S912Q0LEQX',
  );
}
